INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (1, 'ad', 'أندورا', 'Andorra', 'Andorre');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (2, 'ae', 'الإمارات العربية المتحدة', 'United Arab Emirates', 'Emirats Arabes Unis');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (3, 'af', 'أفغانستان', 'Afghanistan', 'L''Afghanistan');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (4, 'ag', 'أنتيغوا وبربودا', 'Antigua and Barbuda', 'Antigua-et-Barbuda');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (5, 'ai', 'أنغيلا', 'Anguilla', 'Anguilla');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (6, 'al', 'ألبانيا', 'Albania', 'Albanie');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (7, 'am', 'أرمينيا', 'Armenia', 'Arménie');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (8, 'an', 'جزر الأنتيل الهولندية', 'Netherlands Antilles', 'Antilles néerlandaises');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (9, 'ao', 'أنغولا', 'Angola', 'Angola');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (10, 'ar', 'الأرجنتين', 'Argentina', 'Argentine');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (11, 'at', 'النمسا', 'Austria', 'L''Autriche');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (12, 'au', 'أستراليا', 'Australia', 'Australie');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (13, 'aw', 'أروبا', 'Aruba', 'Aruba');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (14, 'az', 'أذربيجان', 'Azerbaijan', 'Azerbaïdjan');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (15, 'ba', 'البوسنة والهرسك', 'Bosnia and Herzegovina', 'Bosnie Herzégovine');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (16, 'bb', 'بربادوس', 'Barbados', 'La Barbade');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (17, 'bd', 'بنغلاديش', 'Bangladesh', 'Bangladesh');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (18, 'be', 'بلجيكا', 'Belgium', 'Belgique');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (19, 'bf', 'بوركينا فاسو', 'Burkina Faso', 'Burkina Faso');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (20, 'bg', 'بلغاريا', 'Bulgaria', 'Bulgarie');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (21, 'bh', 'البحرين', 'Bahrain', 'Bahreïn');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (22, 'bi', 'بوروندي', 'Burundi', 'Burundi');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (23, 'bj', 'بنين', 'Benin', 'Bénin');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (24, 'bm', 'برمودا', 'Bermuda', 'Bermudes');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (25, 'bn', 'بروناي دار السلام', 'Brunei Darussalam', 'Brunei Darussalam');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (26, 'bo', 'بوليفيا', 'Bolivia', 'Bolivie');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (27, 'br', 'البرازيل', 'Brazil', 'Brésil');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (28, 'bs', 'الباهاما', 'Bahamas', 'Bahamas');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (29, 'bt', 'بوتان', 'Bhutan', 'Bhoutan');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (30, 'bw', 'بوتسوانا', 'Botswana', 'Botswana');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (31, 'by', 'روسيا البيضاء', 'Belarus', 'Biélorussie');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (32, 'bz', 'بليز', 'Belize', 'Belize');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (33, 'ca', 'كندا', 'Canada', 'Canada');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (34, 'cc', 'جزر كوكوس (كيلينغ)', 'Cocos (Keeling) Islands', 'Îles Cocos (Keeling)');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (35, 'cd', 'جمهورية الكونغو الديموقراطية', 'Democratic Republic of the Congo', 'République Démocratique du Congo');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (36, 'cf', 'جمهورية افريقيا الوسطى', 'Central African Republic', 'République centrafricaine');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (37, 'cg', 'الكونغو', 'Congo', 'Congo');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (38, 'ch', 'سويسرا', 'Switzerland', 'Suisse');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (39, 'ci', 'ساحل العاج (ساحل العاج)', 'Cote D''Ivoire (Ivory Coast)', 'Cote D''Ivoire (Côte d''Ivoire)');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (40, 'ck', 'جزر كوك', 'Cook Islands', 'les Îles Cook');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (41, 'cl', 'تشيلي', 'Chile', 'Chili');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (42, 'cm', 'الكاميرون', 'Cameroon', 'Cameroun');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (43, 'cn', 'الصين', 'China', 'Chine');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (44, 'co', 'كولومبيا', 'Colombia', 'Colombie');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (45, 'cr', 'كوستا ريكا', 'Costa Rica', 'Costa Rica');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (46, 'cu', 'كوبا', 'Cuba', 'Cuba');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (47, 'cv', 'الرأس الأخضر', 'Cape Verde', 'Cap-Vert');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (48, 'cx', 'جزيرة الكريسماس', 'Christmas Island', 'L''île de noël');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (49, 'cy', 'قبرص', 'Cyprus', 'Chypre');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (50, 'cz', 'جمهورية التشيك', 'Czech Republic', 'République Tchèque');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (51, 'de', 'ألمانيا', 'Germany', 'Allemagne');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (52, 'dj', 'جيبوتي', 'Djibouti', 'Djibouti');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (53, 'dk', 'الدنمارك', 'Denmark', 'Danemark');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (54, 'dm', 'دومينيكا', 'Dominica', 'Dominique');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (55, 'do', 'جمهورية الدومنيكان', 'Dominican Republic', 'République Dominicaine');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (56, 'dz', 'الجزائر', 'Algeria', 'Algérie');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (57, 'ec', 'الإكوادور', 'Ecuador', 'L''Équateur');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (58, 'ee', 'استونيا', 'Estonia', 'Estonie');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (59, 'eg', 'مصر', 'Egypt', 'Egypte');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (60, 'eh', 'الصحراء الغربية', 'Western Sahara', 'Sahara occidental');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (61, 'er', 'إريتريا', 'Eritrea', 'Erythrée');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (62, 'es', 'إسبانيا', 'Spain', 'Espagne');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (63, 'et', 'أثيوبيا', 'Ethiopia', 'Ethiopie');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (64, 'fi', 'فنلندا', 'Finland', 'Finlande');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (65, 'fj', 'فيجي', 'Fiji', 'Fidji');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (66, 'fk', 'جزر فوكلاند (مالفيناس)', 'Falkland Islands (Malvinas)', 'Iles Malouines (Malouines)');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (67, 'fm', 'ولايات ميكرونيزيا الموحدة', 'Federated States of Micronesia', 'États fédérés de Micronésie');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (68, 'fo', 'جزر صناعية', 'Faroe Islands', 'Îles Féroé');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (69, 'fr', 'فرنسا', 'France', 'France');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (70, 'ga', 'الغابون', 'Gabon', 'Gabon');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (71, 'gb', 'بريطانيا العظمى (المملكة المتحدة)', 'Great Britain (UK)', 'Grande-Bretagne (UK)');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (72, 'gd', 'غرينادا', 'Grenada', 'Grenade');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (73, 'ge', 'جورجيا', 'Georgia', 'Géorgie');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (74, 'gf', 'غيانا الفرنسية', 'French Guiana', 'Guinée Française');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (75, 'gg', 'لا شيء', 'NULL', 'NUL');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (76, 'gh', 'غانا', 'Ghana', 'Ghana');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (77, 'gi', 'جبل طارق', 'Gibraltar', 'Gibraltar');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (78, 'gl', 'الأرض الخضراء', 'Greenland', 'Groenland');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (79, 'gm', 'غامبيا', 'Gambia', 'Gambie');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (80, 'gn', 'غينيا', 'Guinea', 'Guinée');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (81, 'gp', 'جوادلوب', 'Guadeloupe', 'La guadeloupe');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (82, 'gq', 'غينيا الإستوائية', 'Equatorial Guinea', 'Guinée Équatoriale');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (83, 'gr', 'اليونان', 'Greece', 'Grèce');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (84, 'gs', 'جورجيا وجزر ساندويتش', 'S. Georgia and S. Sandwich Islands', 'Géorgie du Sud et les îles Sandwich du Sud');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (85, 'gt', 'غواتيمالا', 'Guatemala', 'Guatemala');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (86, 'gw', 'غينيا بيساو', 'Guinea-Bissau', 'Guinée-Bissau');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (87, 'gy', 'غيانا', 'Guyana', 'Guyane');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (88, 'hk', 'هونغ كونغ', 'Hong Kong', 'Hong Kong');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (89, 'hn', 'هندوراس', 'Honduras', 'Honduras');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (90, 'hr', 'كرواتيا (هرفاتسكا)', 'Croatia (Hrvatska)', 'Croatie (Hrvatska)');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (91, 'ht', 'هايتي', 'Haiti', 'Haïti');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (92, 'hu', 'اليونان', 'Hungary', 'Hongrie');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (93, 'id', 'أندونيسيا', 'Indonesia', 'Indonésie');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (94, 'ie', 'أيرلندا', 'Ireland', 'Irlande');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (96, 'in', 'الهند', 'India', 'Inde');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (97, 'iq', 'العراق', 'Iraq', 'Irak');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (98, 'ir', 'إيران', 'Iran', 'Iran');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (99, 'is', 'أيسلندا', 'Iceland', 'Islande');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (100, 'it', 'إيطاليا', 'Italy', 'Italie');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (101, 'jm', 'جامايكا', 'Jamaica', 'Jamaïque');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (102, 'jo', 'الأردن', 'Jordan', 'Jordan');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (103, 'jp', 'اليابان', 'Japan', 'Japon');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (104, 'ke', 'كينيا', 'Kenya', 'Kenya');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (105, 'kg', 'قرغيزستان', 'Kyrgyzstan', 'Kirghizistan');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (106, 'kh', 'كمبوديا', 'Cambodia', 'Cambodge');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (107, 'ki', 'كيريباس', 'Kiribati', 'Kiribati');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (108, 'km', 'جزر القمر', 'Comoros', 'Comores');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (109, 'kn', 'سانت كيتس ونيفيس', 'Saint Kitts and Nevis', 'Saint-Christophe-et-Niévès');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (110, 'kp', 'كوريا الشمالية', 'Korea (North)', 'Corée du Nord');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (111, 'kr', 'كوريا، جنوب)', 'Korea (South)', 'COREE DU SUD)');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (112, 'kw', 'الكويت', 'Kuwait', 'Koweit');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (113, 'ky', 'جزر كايمان', 'Cayman Islands', 'Îles Caïmans');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (114, 'kz', 'كازاخستان', 'Kazakhstan', 'Le kazakhstan');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (115, 'la', 'لاوس', 'Laos', 'Laos');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (116, 'lb', 'لبنان', 'Lebanon', 'Liban');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (117, 'lc', 'القديسة لوسيا', 'Saint Lucia', 'Sainte-Lucie');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (118, 'li', 'ليختنشتاين', 'Liechtenstein', 'Le Liechtenstein');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (119, 'lk', 'سيريلانكا', 'Sri Lanka', 'Sri Lanka');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (120, 'lr', 'ليبيريا', 'Liberia', 'Libéria');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (121, 'ls', 'ليسوتو', 'Lesotho', 'Lesotho');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (122, 'lt', 'ليتوانيا', 'Lithuania', 'Lituanie');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (123, 'lu', 'لوكسمبورغ', 'Luxembourg', 'Luxembourg');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (124, 'lv', 'لاتفيا', 'Latvia', 'Lettonie');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (125, 'ly', 'ليبيا', 'Libya', 'Libye');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (126, 'ma', 'المغرب', 'Morocco', 'Maroc');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (127, 'mc', 'موناكو', 'Monaco', 'Monaco');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (128, 'md', 'مولدوفا', 'Moldova', 'La Moldavie');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (129, 'mg', 'مدغشقر', 'Madagascar', 'Madagascar');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (130, 'mh', 'جزر مارشال', 'Marshall Islands', 'Iles Marshall');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (131, 'mk', 'مقدونيا', 'Macedonia', 'Macédoine');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (132, 'ml', 'مالي', 'Mali', 'Mali');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (133, 'mm', 'ميانمار', 'Myanmar', 'Myanmar');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (134, 'mn', 'منغوليا', 'Mongolia', 'Mongolie');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (135, 'mo', 'ماكاو', 'Macao', 'Macao');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (136, 'mp', 'جزر مريانا الشمالية', 'Northern Mariana Islands', 'Îles Mariannes du Nord');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (137, 'mq', 'مارتينيك', 'Martinique', 'Martinique');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (138, 'mr', 'موريتانيا', 'Mauritania', 'Mauritanie');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (139, 'ms', 'مونتسيرات', 'Montserrat', 'Montserrat');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (140, 'mt', 'مالطا', 'Malta', 'Malte');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (141, 'mu', 'موريشيوس', 'Mauritius', 'Maurice');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (142, 'mv', 'جزر المالديف', 'Maldives', 'Maldives');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (143, 'mw', 'مالاوي', 'Malawi', 'Malawi');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (144, 'mx', 'المكسيك', 'Mexico', 'Mexique');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (145, 'my', 'ماليزيا', 'Malaysia', 'Malaisie');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (146, 'mz', 'موزمبيق', 'Mozambique', 'Mozambique');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (147, 'na', 'ناميبيا', 'Namibia', 'Namibie');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (148, 'nc', 'كاليدونيا الجديدة', 'New Caledonia', 'Nouvelle Calédonie');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (149, 'ne', 'النيجر', 'Niger', 'Niger');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (150, 'nf', 'جزيرة نورفولك', 'Norfolk Island', 'l''ile de Norfolk');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (151, 'ng', 'نيجيريا', 'Nigeria', 'Nigeria');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (152, 'ni', 'نيكاراغوا', 'Nicaragua', 'Nicaragua');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (153, 'nl', 'هولندا', 'Netherlands', 'Pays-Bas');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (154, 'no', 'النرويج', 'Norway', 'Norvège');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (155, 'np', 'نيبال', 'Nepal', 'Népal');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (156, 'nr', 'ناورو', 'Nauru', 'Nauru');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (157, 'nu', 'نيوي', 'Niue', 'Niue');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (158, 'nz', 'نيوزيلندا (اوتياروا)', 'New Zealand (Aotearoa)', 'Nouvelle-Zélande (Aotearoa)');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (159, 'om', 'سلطنة عمان', 'Oman', 'Oman');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (160, 'pa', 'بناما', 'Panama', 'Panama');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (161, 'pe', 'بيرو', 'Peru', 'Pérou');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (162, 'pf', 'بولينيزيا الفرنسية', 'French Polynesia', 'Polynésie française');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (163, 'pg', 'بابوا غينيا الجديدة', 'Papua New Guinea', 'Papouasie Nouvelle Guinée');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (164, 'ph', 'الفلبين', 'Philippines', 'Philippines');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (165, 'pk', 'باكستان', 'Pakistan', 'Pakistan');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (166, 'pl', 'بولندا', 'Poland', 'Pologne');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (167, 'pm', 'سانت بيير وميكلون', 'Saint Pierre and Miquelon', 'Saint Pierre et Miquelon');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (168, 'pn', 'بيتكيرن', 'Pitcairn', 'Pitcairn');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (169, 'ps', 'الأراضي الفلسطينية', 'Palestinian Territory', 'Territoire Palestinien');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (170, 'pt', 'البرتغال', 'Portugal', 'le Portugal');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (171, 'pw', 'بالاو', 'Palau', 'Palau');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (172, 'py', 'باراغواي', 'Paraguay', 'Paraguay');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (173, 'qa', 'دولة قطر', 'Qatar', 'Qatar');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (174, 're', 'جمع شمل', 'Reunion', 'Réunion');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (175, 'ro', 'رومانيا', 'Romania', 'Roumanie');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (176, 'ru', 'الاتحاد الروسي', 'Russian Federation', 'Fédération Russe');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (177, 'rw', 'رواندا', 'Rwanda', 'Rwanda');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (178, 'sa', 'المملكة العربية السعودية', 'Saudi Arabia', 'Arabie Saoudite');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (179, 'sb', 'جزر سليمان', 'Solomon Islands', 'Les îles Salomon');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (180, 'sc', 'سيشيل', 'Seychelles', 'les Seychelles');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (181, 'sd', 'سودان', 'Sudan', 'Soudan');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (182, 'se', 'السويد', 'Sweden', 'Suède');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (183, 'sg', 'سنغافورة', 'Singapore', 'Singapour');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (184, 'sh', 'سانت هيلانة', 'Saint Helena', 'Sainte Hélène');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (185, 'si', 'سلوفينيا', 'Slovenia', 'La slovénie');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (186, 'sj', 'سفالبارد وجان مايان', 'Svalbard and Jan Mayen', 'Svalbard et Jan Mayen');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (187, 'sk', 'سلوفاكيا', 'Slovakia', 'La slovaquie');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (188, 'sl', 'سيرا ليون', 'Sierra Leone', 'Sierra Leone');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (189, 'sm', 'سان مارينو', 'San Marino', 'Saint Marin');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (190, 'sn', 'السنغال', 'Senegal', 'Sénégal');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (191, 'so', 'الصومال', 'Somalia', 'Somalie');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (192, 'sr', 'سورينام', 'Suriname', 'Suriname');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (193, 'st', 'ساو تومي وبرنسيبي', 'Sao Tome and Principe', 'Sao Tomé et Principe');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (194, 'sv', 'السلفادور', 'El Salvador', 'Le Salvador');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (195, 'sy', 'سوريا', 'Syria', 'Syrie');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (196, 'sz', 'سوازيلاند', 'Swaziland', 'Swaziland');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (197, 'tc', 'جزر تركس وكايكوس', 'Turks and Caicos Islands', 'îles Turques-et-Caïques');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (198, 'td', 'تشاد', 'Chad', 'Le tchad');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (199, 'tf', 'المناطق الجنوبية لفرنسا', 'French Southern Territories', 'Terres australes françaises');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (200, 'tg', 'ليذهب', 'Togo', 'Aller');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (201, 'th', 'تايلاند', 'Thailand', 'Thaïlande');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (202, 'tj', 'طاجيكستان', 'Tajikistan', 'Tadjikistan');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (203, 'tk', 'توكيلاو', 'Tokelau', 'Tokelau');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (204, 'tm', 'تركمانستان', 'Turkmenistan', 'Turkménistan');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (205, 'tn', 'تونس', 'Tunisia', 'Tunisie');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (206, 'to', 'تونغا', 'Tonga', 'Tonga');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (207, 'tr', 'ديك رومي', 'Turkey', 'dinde');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (208, 'tt', 'ترينداد وتوباغو', 'Trinidad and Tobago', 'Trinité-et-Tobago');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (209, 'tv', 'توفالو', 'Tuvalu', 'Tuvalu');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (210, 'tw', 'تايوان', 'Taiwan', 'Taïwan');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (211, 'tz', 'تنزانيا', 'Tanzania', 'Tanzanie');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (212, 'ua', 'أوكرانيا', 'Ukraine', 'Ukraine');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (213, 'ug', 'أوغندا', 'Uganda', 'Ouganda');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (214, 'uy', 'أوروغواي', 'Uruguay', 'Uruguay');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (215, 'uz', 'أوزبكستان', 'Uzbekistan', 'Ouzbékistan');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (216, 'vc', 'سانت فنسنت وجزر غرينادين', 'Saint Vincent and the Grenadines', 'Saint-Vincent-et-les-Grenadines');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (217, 've', 'فنزويلا', 'Venezuela', 'Venezuela');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (218, 'vg', 'جزر العذراء البريطانية)', 'Virgin Islands (British)', 'Îles vierges britanniques');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (219, 'vi', 'جزر فيرجن (الولايات المتحدة)', 'Virgin Islands (U.S.)', 'Îles Vierges (États-Unis)');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (220, 'vn', 'فيتنام', 'Viet Nam', 'Viet Nam');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (221, 'vu', 'فانواتو', 'Vanuatu', 'Vanuatu');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (222, 'wf', 'واليس وفوتونا', 'Wallis and Futuna', 'Wallis et Futuna');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (223, 'ws', 'ساموا', 'Samoa', 'Samoa');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (224, 'ye', 'اليمن', 'Yemen', 'Yémen');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (225, 'yt', 'مايوت', 'Mayotte', 'Mayotte');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (226, 'za', 'جنوب أفريقيا', 'South Africa', 'Afrique du Sud');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (227, 'zm', 'زامبيا', 'Zambia', 'Zambie');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (228, 'zr', 'زائير (سابقة)', 'Zaire (former)', 'Zaïre (ancien)');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (229, 'zw', 'زيمبابوي', 'Zimbabwe', 'Zimbabwe');
INSERT INTO ecovve_db.countries (id, code, name_ar, name_en, name_fr) VALUES (230, 'us', 'الولايات المتحدة', 'United States of America', 'les États-Unis d''Amérique');